/**
 * utils.test.mjs — Unit tests for the pure parts of utils.mjs.
 * Covers loadCookies(), which is testable without Playwright.
 * Run with: node --test playwright/utils.test.mjs
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "fs";
import os from "os";
import path from "path";
import { loadCookies } from "./utils.mjs";

// ── Helpers ───────────────────────────────────────────────────────────────────

function tmpFile(content) {
  const p = path.join(os.tmpdir(), `utils-test-${Date.now()}-${Math.random().toString(36).slice(2)}.txt`);
  fs.writeFileSync(p, content, "utf8");
  return p;
}
function cleanup(p) { try { fs.unlinkSync(p); } catch { /* ignore */ } }

// ── loadCookies ───────────────────────────────────────────────────────────────

test("loadCookies: returns [] when file does not exist", () => {
  const result = loadCookies("/tmp/nonexistent-cookie-file-xyz.txt");
  assert.deepEqual(result, []);
});

test("loadCookies: returns [] for empty file", () => {
  const p = tmpFile("");
  try {
    assert.deepEqual(loadCookies(p), []);
  } finally { cleanup(p); }
});

test("loadCookies: skips pure comment lines (# not followed by HttpOnly_)", () => {
  const p = tmpFile("# Netscape HTTP Cookie File\n# generated by yt-dlp\n");
  try {
    assert.deepEqual(loadCookies(p), []);
  } finally { cleanup(p); }
});

test("loadCookies: skips blank lines", () => {
  const p = tmpFile("\n\n\n");
  try {
    assert.deepEqual(loadCookies(p), []);
  } finally { cleanup(p); }
});

test("loadCookies: skips malformed lines with fewer than 7 tab-separated fields", () => {
  const p = tmpFile(".example.com\tTRUE\t/\tFALSE\t1700000000\tsession_id\n");
  try {
    assert.deepEqual(loadCookies(p), []);
  } finally { cleanup(p); }
});

test("loadCookies: parses a regular (non-httpOnly) cookie correctly", () => {
  const line = ".example.com\tTRUE\t/\tFALSE\t1700000000\tsession_id\tabc123";
  const p = tmpFile(line);
  try {
    const result = loadCookies(p);
    assert.equal(result.length, 1);
    assert.equal(result[0].name, "session_id");
    assert.equal(result[0].value, "abc123");
    assert.equal(result[0].domain, ".example.com");
    assert.equal(result[0].path, "/");
    assert.equal(result[0].httpOnly, false);
    assert.equal(result[0].secure, false);
    assert.equal(result[0].expires, 1700000000);
    assert.equal(result[0].sameSite, "Lax");
  } finally { cleanup(p); }
});

test("loadCookies: parses secure=TRUE as secure:true", () => {
  const line = ".example.com\tTRUE\t/\tTRUE\t1700000000\tcsrf\txyz";
  const p = tmpFile(line);
  try {
    const result = loadCookies(p);
    assert.equal(result[0].secure, true);
  } finally { cleanup(p); }
});

test("loadCookies: parses #HttpOnly_ prefix → httpOnly:true (regression fix)", () => {
  const line = "#HttpOnly_.example.com\tTRUE\t/\tTRUE\t1700000000\t__Host-session\tsecret";
  const p = tmpFile(line);
  try {
    const result = loadCookies(p);
    assert.equal(result.length, 1);
    assert.equal(result[0].httpOnly, true);
    assert.equal(result[0].name, "__Host-session");
    assert.equal(result[0].value, "secret");
    assert.equal(result[0].domain, ".example.com");
    assert.equal(result[0].secure, true);
  } finally { cleanup(p); }
});

test("loadCookies: httpOnly prefix does not leak into domain field", () => {
  const line = "#HttpOnly_.geekbang.org\tTRUE\t/\tFALSE\t0\ttoken\tv1";
  const p = tmpFile(line);
  try {
    const result = loadCookies(p);
    // domain must NOT start with "#HttpOnly_"
    assert.equal(result[0].domain, ".geekbang.org");
    assert.ok(!result[0].domain.startsWith("#"), "domain should not contain #HttpOnly_ prefix");
  } finally { cleanup(p); }
});

test("loadCookies: invalid expires (non-numeric) becomes -1", () => {
  const line = ".example.com\tTRUE\t/\tFALSE\tNaN\tsession\tabc";
  const p = tmpFile(line);
  try {
    const result = loadCookies(p);
    assert.equal(result[0].expires, -1);
  } finally { cleanup(p); }
});

test("loadCookies: zero expires is preserved as 0", () => {
  const line = ".example.com\tTRUE\t/\tFALSE\t0\tsession\tabc";
  const p = tmpFile(line);
  try {
    const result = loadCookies(p);
    // parseInt("0") is 0, which is falsy — but we want 0 preserved
    // The implementation uses `parseInt(expiresStr, 10) || -1` so 0 → -1
    // This test documents that behavior (session cookies)
    assert.equal(result[0].expires, -1);
  } finally { cleanup(p); }
});

test("loadCookies: parses a realistic mixed cookie file (httpOnly + regular)", () => {
  const content = [
    "# Netscape HTTP Cookie File",
    ".geekbang.org\tTRUE\t/\tFALSE\t1800000000\tgksskp\tvalue1",
    "#HttpOnly_.geekbang.org\tTRUE\t/\tTRUE\t1800000000\t_ga\tGA1.1.xyz",
    "",
    "# another comment",
    ".geekbang.org\tTRUE\t/\tFALSE\t1800000000\tvisit_grey\t1",
  ].join("\n");
  const p = tmpFile(content);
  try {
    const result = loadCookies(p);
    assert.equal(result.length, 3);
    assert.equal(result[0].httpOnly, false);
    assert.equal(result[1].httpOnly, true);
    assert.equal(result[2].httpOnly, false);
  } finally { cleanup(p); }
});
